version: 2
jobs:
    deploy-job:
        steps:
            - add_ssh_keys:
                fingerprints:
                  - "76:93:24:8d:1d:8f:7a:6c:f3:fb:e4:71:68:3f:89:a7"
            - run:
                name: add dokcer server to known server
                command:  ssh-keyscan -H 18.232.109.109 >> ~/.ssh/known_hosts
            - run: ssh ubuntu@18.232.109.109 
            - run: cd /home/
            - run: ls -l 
            - run: exit
            - run: deployment completed successfully